sudo: required

language: java

jdk:
  - oraclejdk8
  - oraclejdk9

before_install:
  - git config --global user.email "travis-ci@travis-ci.org"
  - git config --global user.name "Travis CI"

before_script:
  - chmod +x scripts/build.sh

script: ./scripts/build.sh --init

branches:
  only: 'master'

cache:
  directories:
    - '$HOME/.m2/repository'
